### ISSUE TITLE
[RelativeTimeFormat] Spec alignment

### ISSUE THREAD

**Issue by wessberg** [catamphetamine/javascript-time-ago#15]
Hi there. Great work on this library!
I'm assessing polyfills for `Intl.RelativeTimeFormat` and have been looking at your library.

There are a few things that is out of sync with the specification that I think is worth looking into addressing:

- [The `numeric` option](https://github.com/tc39/proposal-intl-relative-time#numeric) is not defined. Instead, you accept an option called `type` which can be either `"numeric"` or `"text"`, however this option is never actually used. As it is right now, consumers of your implementation will always get numeric values back, instead of things like, say, `yesterday` in the English locales.

- [`formatToParts`](https://github.com/tc39/proposal-intl-relative-time#intlrelativetimeformatprototypeformattopartsvalue-unit) incorrectly report the `unit` as the `type`. For example, calling `formatToParts(-1, "day")` with `en` as the locale will return: `[{type: "day", value: "1"}, {type: "literal", value: " day ago"}]`. However, the expected return value according to the Spec would be: `[{type: "integer", value: "1", unit: "day"}, {type: "literal", value: " day ago"}]`

**Comment by catamphetamine** [comment]
@wessberg Hello.
Yes, the points you outlined are worth discussing.
If this library is gonna be a compliant polyfill then it will have to emulate the exact behavior of the spec.
However, is the spec still a draft or has it been released already?
I guess it's still a draft in which case we won't need to comply to it exactly.

> The numeric option is not defined. Instead, you accept an option called type which can be either "numeric" or "text", however this option is never actually used. As it is right now, consumers of your implementation will always get numeric values back, instead of things like, say, yesterday in the English locales.

Yes, the reason I didn't add non-numeric types is because it's unclear why did they add it.
For example, if it's `00:05` on the user's clock and the time of an event is `23:55` then it will say "yesterday" while in reality it should have been "10 min ago" so "yesterday" is confusing.

Quoting the spec draft:

> If numeric:auto option is passed, it will produce the string yesterday or tomorrow instead of 1 day ago or in 1 day, this allows to not always have to use numeric values in the output.

So I don't see any sense in making such substitution: it will only confuse the user in many cases.
And it's still not a breaking feature because the program won't crash or anything: it will still say "in 1 day" which is perfectly fine and doesn't confuse anyone.

> formatToParts incorrectly report the unit as the type. For example, calling formatToParts(-1, "day") with en as the locale will return: [{type: "day", value: "1"}, {type: "literal", value: " day ago"}]. However, the expected return value according to the Spec would be: [{type: "integer", value: "1", unit: "day"}, {type: "literal", value: " day ago"}]

I guess perhaps they changed it because I'd notice it when implementing `formatToParts` that time.

We could introduce a special setting on the `RelativeTimeFormat` class.
Something like `RelativeTimeFormat.useVersion(2)` which would enable the new API.

If you want, you can add the `yesterday` thing and the new `formatToParts` thing along with the `RelativeTimeFormat.useVersion(2)` feature in a Pull Request.
I'd do it anyway if the spec got released.
As I already said, I guess it's still a draft.

**Comment by catamphetamine** [comment]
@wessberg On second thought, I'll add these features myself. Will release soon.

**Comment by catamphetamine** [comment]
@wessberg 
Released `javascript-time-ago@1.0.35` with `RelativeTimeFormat.useVersion(2)`.
Perhaps you could also bump this thread:
https://github.com/tc39/proposal-intl-relative-time/issues/55
I don't get any feedback from the spec authors on this polyfill.
And they seem to not willing to add a link to it in their README.

**Comment by catamphetamine** [comment]
@wessberg Released `Intl.RelativeTimeFormat` polyfill as a separate package:
https://github.com/catamphetamine/relative-time-format
